### ISSUE TITLE
kubernetes: docker version too high for k8s ...

### ISSUE THREAD

**Issue by chrisohaver** [coredns/ci#75]
Docker version is higher than _kubeadm_ will allow, causing cluster creation to fail.
need to figure out how to get _minikube_ to tell _kubeadm_ ignore this (i.e. `--ignore-preflight-checks`).

**Comment by chrisohaver** [comment]
@miekg FYI

**Comment by miekg** [comment]
[ Quoting <notifications@github.com> in "Re: [coredns/ci] kubernetes: docker..." ]
>@miekg FYI

oh damn. And then it refuses to do anything?

**Comment by chrisohaver** [comment]
Yes - had trouble downgrading docker yesterday. 
Will continue troubleshooting today.

**Comment by chrisohaver** [comment]
I re-downgraded docker to 17.03 - the highest version permitted by `kubeadm`, and it is in itself functional.  But the CI still fails, now in a different stage, because our Dockerfile requires a higher version of Docker to compile ...  ugh.

A couple of options:
1. compile our own version of minikube that tells kubeadm to ignore the docker version. (this does require a compile of minikube, the kubeadm flags are hard coded)
2. move away from minikube and directly use `kubeadm`  - would take 4-5 days i think.  lots of fiddly details to automate (which is precisely why we use minikube)

I'll start with 1 ...

**Comment by chrisohaver** [comment]
I've got minikube compiled with the option to ignore docker version diffs... 
minkube now successfully brings up a cluster, but 1/3 of the CI tests fail due to coredns not coming up in time.

**Comment by miekg** [comment]
Our docker file? What's the error? Can we just patch that out in the ci?
You just need coredns in a docker container nothing more. Don't need
multistage,.don't need certs

Seems easier to use a different Docker file altogether

**Comment by chrisohaver** [comment]
fixed with #76...  newer version of k8s uses coredns by default, and manages it with add on manager, which was clobbering the tests in progress.
