### ISSUE TITLE
Move Kubernetes install from Minikube to K8s docker-in-docker

### ISSUE THREAD

**Issue by rajansandeep** [coredns/ci#94]
We can eventually move our cluster deployment from Minikube to Kubernetes DinD (Either https://github.com/kubernetes-sigs/kind or https://github.com/kubernetes-sigs/kubeadm-dind-cluster).

- We will be able to run tests concurrently as we can deploy multiple clusters.
- Move closer to how Kubernetes is tested as even the kubernetes test uses k8s DinD.

**Comment by chrisohaver** [comment]
@rajansandeep, Is this still relevant after having migrated to circle ci?

**Comment by rajansandeep** [comment]
Yes, we can still look into moving the tests from minikube to kind or kubeadm-dind

**Comment by rajansandeep** [comment]
Done by moving to Kind in https://github.com/coredns/ci/pull/115
